### PR TITLE
rewrite ctre config functionally

### PR DESCRIPTION
**Pull request by lmaxwell24**
using functional methods, rewrite the configuration (PID and encoder setting) of the drive subsystem

a few new functions of note:
```py
def configCtre(x: Tuple[str, ErrorCode]) -> bool:
    return not ctreCheckError(x[0], x[1])
# passes a tuple of two items into check error, returns true if error 

foldl = lambda func, acc, xs: (functools.)reduce(func, xs, acc)
# haskell-like foldl function, for reducing all the errors to a single possible error true value

orFunc = lambda x, y: x or y
# python or but as a function with 2 arguments
```

the current implementation is to take a list of tuples, map through them from the tuple into a value if they gave an error, and then condense all the errors into one possible error, and return if there is an error

!!NOTE!!: this will attempt all configuration settings before exiting, if there is any error along the way it will not be accounted for until all other functions have returned

### CODE REVIEW

**Review by LandonBayer — APPROVED** [review]

**Review by icai0 — APPROVED** [review]

**Comment by lmaxwell24** [comment]
tested on actual hardware, working with no hiccups

**Review by caloisio — CHANGES_REQUESTED** [review]
Though the current code returns the first error, it still executes every function during tuple construction, regardless of error status. Consider the following example:
```python
from typing import Tuple

def returnTrue() -> bool:
    print("returnTrue called")
    return True

def returnFalse() -> bool:
    print("returnFalse called")
    return False

def example() -> None:
    def ctreCheckError(name: str, errorCode: bool) -> bool:
        if (errorCode is not None) and (errorCode != True):
            print(f"ERROR: {name}: {errorCode}")
            return False
        return True

    def configCtre(x: Tuple[str, bool]) -> bool:
        return not ctreCheckError(x[0], x[1])
        
    configSettings = [
        (
            "returnTrue",
            returnTrue(),
        ),
        (
            "returnFalse",
            returnFalse(),
        ),
        (
            "returnTrue",
            returnTrue(),
        ),
    ]

    for config in configSettings:
        if configCtre(config):
            return

example()
```
The output is:
```
returnTrue called
returnFalse called
returnTrue called
ERROR: returnFalse: False
```

Rather than stopping on first error which would be:
```
returnTrue called
returnFalse called
ERROR: returnFalse: False
```

**Comment by caloisio** [comment]
I'm not sure these changes pass the smell test for me. They don't really reduce the size of the code, they add additional indirection/complexity (config tuple, unpacking), and all in a section of code that was performing fine (as far as I am aware) with straightforward code. If the changes opened up additional needed functionality or improved performance or correctness that would be another matter. Willing to listen to differing opinions and @agelsomini feel free to over-rule for the mentor-level approval, maybe I'm biased from writing the original code :smile:

**Comment by caloisio** [comment]
Let's refine what requirements motivated these changes (we can create an `issue` to capture them and link this PR to it) to identify what the root issue(s) is(are) and then more directly design/implement against what we find. If it's general code cleanup/refactoring that's fine, we should just make sure we understand what the target result is so that we can uniformly apply that standard across the rest of the code-base. @lmaxwell24 if you have time, would you mind creating the issue and starting it off (it will probably evolve a bit over time)?

**Comment by lmaxwell24** [comment]
Not needed anymore, closing

**Pull request closed without merging**
